class AppStrings {
  AppStrings._();
  static const String onboardingTitle1 = 'Explore Upcoming and Nearby Events';
  static const String onboardingDescription1 =
      'In publishing and graphic design, Lorem is a placeholder text commonly';
  static const String onboardingTitle2 =
      'We Have Modern Events Calendar Feature';
  static const String onboardingDescription2 =
      'In publishing and graphic design, Lorem is a placeholder text commonly';
  static const String onboardingTitle3 =
      'To Look Up More Events or Activities Nearby By Map';
  static const String onboardingDescription3 =
      'In publishing and graphic design, Lorem is a placeholder text commonly';
  static const String skip = 'Skip';
  static const String next = 'Next';
  static const String done = 'Done';
  static const String welcome = 'Welcome';
  static const String getStarted = 'Get Started';
  static const String signIn = 'Sign in';
  static const String email = 'abc@email.com';
  static const String password = 'Your password';
  static const String rememberMe = 'Remember Me';
  static const String forgotPassword = 'Forgot Password?';
  static const String or = 'OR';
  static const String loginWithGoogle = 'Login with Google';
  static const String loginWithFacebook = 'Login with Facebook';
  static const String dontHaveAccount = 'Don’t have an account?';
  static const String alreadyHaveAccount = 'Already have an account?';
  static const String signUp = 'Sign up';
  static const String confirmPassword = 'Confirm password';
  static const String fullName = 'Full name';
  static const String eventDetails = 'Event Details';
  static String going(int count) => '+$count Going';
  static const String invite = 'Invite';
  static const String internationalBandMusicConcert =
      'International Band Music Concert';
  static const String eventDate = '14 December, 2021';
  static const String eventTime = 'Tuesday, 4:00PM - 9:00PM';
  static const String eventLocation = 'Gala Convention Center';
  static const String eventAddress = '36 Guild Street London, UK ';
  static const String organizerName = 'Ashfak Sayem';
  static const String organizerRole = 'Organizer';
  static const String follow = 'Follow';
  static const String aboutEvent = 'About Event';
  static const String eventDescription =
      'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.';
  static const String readMore = 'Read More...';
  static String buyTicket(String price) => 'Buy Ticket $price';
  static const String events = "Events";
  static const String upcoming = "UPCOMING";
  static const String pastEvents = "PAST EVENTS";
  static const String noUpcomingEvent = "No Upcoming Event";
  static const String noPastEvent = "No Past Event";
  static const String loremIpsum = "Lorem ipsum dolor sit amet, consectetur ";
  static const String exploreEvents = "Explore Events";
  static const String currentLocation = "Current Location";
  static const String newYorkUSA = "New York, USA";
  static const String search = "Search...";
  static const String filters = "Filters";
  static const String sports = "Sports";
  static const String music = "Music";
  static const String food = "Food";
  static const String upcomingEvents = "Upcoming Events";
  static const String seeAll = "See All";
  static const String joMaloneLondon = "Jo Malone London’s Mo..";
  static const String guildStreetLondon = "36 Guild Street London, UK ";
  static const String nearbyYou = "Nearby You";
  static const String explore = "Explore";
  static const String map = "Map";
  static const String profile = "Profile";
  static const String inviteYourFriends = "Invite your friends";
  static const String get20ForTicket = "Get \$20 for ticket";
  static const String eventDay = "10";
  static const String eventMonth = "JUNE";
  static const String myProfile = "My Profile";
  static const String calendar = "Calendar";
  static const String signOut = "Sign Out";
  static const String searchTitle = "Search";
  static const String searchEventDate = "1ST MAY - SAT - 2:00 PM";
  static const String virtualSmoothJazz = "A virtual evening of smooth jazz";
  static const String mothersDay = "Jo malone london’s mother’s day";
  static const String womensLeadership = "Women’s leadership conference";
  static const String kidsSafety = "International kids safe parents night out";
  static const String musicFestival = "International gala music festival";
  static const String filter = "Filter";
  static const String art = "Art";
  static const String timeAndDate = "Time & Date";
  static const String today = "Today";
  static const String tomorrow = "Tomorrow";
  static const String thisWeek = "This week";
  static const String chooseFromCalendar = "Choose from calendar";
  static const String location = "Location";
  static const String selectPriceRange = "Select price range";
  static const String priceRange = "\$20-\$120";
  static const String reset = "RESET";
  static const String apply = "APPLY";
  static const String eventDateMothersDay = "WED, APR 28 - 5:30 PM";
  static const String eventDateJazz = "SAT, MAY 1 - 2:00 PM";
  static const String eventDateLeadership = "SAT, APR 24 - 1:30 PM";
  static const String eventDateKidsSafety = "FRI, APR 23 - 6:00 PM";
  static const String eventDateCollectivity = "MON, JUN 21 - 10:00 PM";
  static const String eventDateFestival = "SUN, APR 25 - 10:15 AM";
  static const String collectivityMusic =
      "Collectivity Plays the Music of Jimi";
  static const String locationGallery = "Radius Gallery - Santa Cruz, CA";
  static const String locationOakland = "Lot 13 - Oakland, CA";
  static const String locationSanFrancisco = "53 Bush St - San Francisco, CA";
  static const String locationLongboard = "Longboard Margarita Bar";
  static const String moreOptions = "More options";
}
